
language: objective-c
xcode_project: STULabel.xcodeproj
osx_image: xcode10.2

script:
- make build-for-testing
- make demo CONFIGURATION=Release LTO=NO
# We only run the tests on the simulator versions not available on CircleCI.
- make test-ios9-iphone-6s 
- make test-ios9-iphone-6s-plus
- make test-ios9-ipad-2
